### PR TITLE
Update composer.lock

### LINKED ISSUE #13: Error
Error: Class "Telegram\MessageId" not found in /app/vendor/skrtdev/novagram/src/Telegram/Types/MessageId.php:11
Stack trace:
#0 /app/vendor/composer/ClassLoader.php(444): include()
#1 /app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(448): Composer\Autoload\ClassLoader->loadClass()
#3 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(413): skrtdev\NovaGram\Bot->createObject()
#4 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(387): skrtdev\NovaGram\Bot->JSONToTelegramObject()
#5 /app/vendor/skrtdev/novagram/src/Telegram/Type.php(76): skrtdev\NovaGram\Bot->APICall()
#6 /app/web/index.php(29): skrtdev\Telegram\Type->__call()
#7 /app/vendor/skrtdev/novagram/src/NovaGram/HandlersTrait.php(101): {closure}()
#8 /app/vendor/skrtdev/novagram/src/NovaGram/HandlersTrait.php(91): skrtdev\NovaGram\Bot->skrtdev\NovaGram\{closure}()
#9 /app/vendor/skrtdev/novagram/src/NovaGram/HandlersTrait.php(76): skrtdev\NovaGram\Bot->skrtdev\NovaGram\{closure}()
#10 /app/vendor/skrtdev/novagram/src/NovaGram/Dispatcher.php(57): skrtdev\NovaGram\Bot->skrtdev\NovaGram\{closure}()
#11 /app/vendor/skrtdev/novagram/src/NovaGram/Dispatcher.php(72): skrtdev\NovaGram\Dispatcher->skrtdev\NovaGram\{closure}()
#12 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(295): skrtdev\NovaGram\Dispatcher->handleUpdate()
#13 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(313): skrtdev\NovaGram\Bot->idle()
#14 [internal function]: skrtdev\NovaGram\Bot->__destruct()
#15 {main}

### PR DESCRIPTION
**Pull request by skrtdev**
Fix #13

### CODE REVIEW

**Comment by SpEcHiDe** [comment]
composer.json ?

**Comment by skrtdev** [comment]
No need to update

**Comment by skrtdev** [comment]
@SpEcHiDe added json payload

**Comment by skrtdev** [comment]
ok all fine

**Pull request merged**
